### PR TITLE
Standardize local and CI testing to use tox

### PR DESCRIPTION
**Pull request by kurtmckee**
This PR introduces the following changes:

* Use tox exclusively to manage test and build environments.
  
  This change standardizes `make` and CI invocations of the test suite.

* Merge Windows testing in with the Linux and macOS test suite.

  This means that Linux and macOS wheels are now getting built and uploaded,
  and also means that coveralls is getting Windows coverage reports.

* Support building wheels for all supported Python versions.

  This is accomplished using a tox label that expands to all supported Python versions.
  Run `tox run -m build` or `make build` to invoke this.

* Support running the test suite across all Python versions in parallel.

  This is accomplished by running `tox run-parallel` or simply `tox p`.
  Cross-environment dependencies, like generating coverage reports after all tests have run,
  are managed in the tox configuration.

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
Nice.
Can you copy/paste the PR description in the commit message?
The idea is to have the patch itself documented, not just the github PR.

**Comment by kurtmckee** [comment]
I've amended the commit and force-pushed. :+1:

Please let me know if there's anything else that you'd like to see with this change.

**Comment by LudovicRousseau** [comment]
Why do you use `choco install swig --version 2.0.12 ...`?
Newer version of swig does not work?

Also I don't think the lines:
```
      - name: "Install build prerequisites (Windows)"
        if: matrix.name == 'Windows'
        run: |
          choco install swig --version 2.0.12 --allow-empty-checksums --yes --limit-output --allow-downgrade
          swig -version
```
are used.
From the logs I see that "Install build prerequisites (Windows)" is never executed.

Maybe the test should be something like `if: matrix.name == 'Windows (x64)'` or `if: contains(matrix.name, 'Windows')`

**Comment by LudovicRousseau** [comment]
tox.ini uses:
```
pylint --errors-only smartcard
```
I think it should be:
```
pylint --errors-only src/smartcard
```
now that the source code has been moved in `src/`.

**Comment by kurtmckee** [comment]
Right you are! This worked locally (showing me a number of items that pylint caught) because I had a cached tox environment that had pyscard installed.

I'm fixing this by removing `skip_install = True`. This will allow pylint to check the module as-installed, rather than checking whatever's in the source tree.

**Comment by kurtmckee** [comment]
### Re: swig version

That's a verbatim lift-and-shift of what was in `windows.yml`. I assumed that that old version was mandatory. I'll remove that downgrade.

### Re: Windows setup steps

Yep, I overlooked that during an update. I'll get that fixed.

**Comment by kurtmckee** [comment]
I've pushed an update that uses `startsWith()` to detect Windows environments, and installs/upgrades swig.

**Pull request merged**
