### PR TITLE
Remove the wxPython dependency

### PR DESCRIPTION
**Pull request by kurtmckee**
This PR introduces the following changes:

* Remove the wxPython code, examples, and `Gui` package extra

`git blame` shows that the `smartcard.wx` module was introduced 17 years ago, in 2007, and that the code itself has been largely untouched except to resolve linter warnings and update copyright years [[example](https://github.com/LudovicRousseau/pyscard/commits/94366134bcd72ad94cbef6f8b3f22e6284eae4f9/smartcard/wx/APDUHexValidator.py?browsing_rename_history=true&new_path=src/smartcard/wx/APDUHexValidator.py&original_branch=master)].

Therefore I'm suggesting to discard the wxPython code because it appears to be unmaintained code.

### CODE REVIEW

**Comment by LudovicRousseau** [comment]
My problem is that I do not know if `smartcard.wx` is used or not by PySCard users.

Since the code is broken since some years I guess the answer is: no.

**Comment by LudovicRousseau** [comment]
```
sudo apt install python3-wxgtk4.0
```

**Comment by kurtmckee** [comment]
Nice! Thanks for suggesting that!

I'm going to be out for a while, so if you've installed wxPython and confirmed that `smartcard.wx` cannot be imported or run, then feel free to merge, otherwise I'll try testing installing from apt when I'm able to. :+1:

**Comment by kurtmckee** [comment]
I ended up having an opportunity to install and try running the app in `SimpleSCardApp.py` and found that a window opened but didn't render anything. Eventually I received a KDE pop-up stating that the window wasn't responding and asking if I wanted to kill the process.

Based on the age of the `smartcard.wx` code and the experience described above, I recommend merging this PR.

**Comment by LudovicRousseau** [comment]
I just fixed `smartcard.wx` issues.
`Examples/wx/readerviewer` works fine for me. Same thing for the other examples.

**Comment by kurtmckee** [comment]
While the code is fixable, I don't recommend keeping code in the package that isn't maintained.

It's okay with me if you close this PR; I'll leave it to you how to proceed.

**Comment by LudovicRousseau** [comment]
The wxPython code does not require any maintenance (it was easy to fix for Python 3). I guess it is not used at all.

So I do not plan to remove it now.

**Pull request closed without merging**
