### PR TITLE
Build Windows binaries also for Python 3.11

### PR DESCRIPTION
**Pull request by bittner**
Makes pyscard available for Python 3.11 as a downloadable installation artifact.

### CODE REVIEW

**Comment by bittner** [comment]
Seems to work fine on AppVeyor.

**Comment by bittner** [comment]
Looks good! Ready to merge. 🚀

**Comment by LudovicRousseau** [comment]
OK to add support of Python 3.11

But if the generation of MSI is disabled in recent versions of setuptools then I propose to drop the generation of MSI installers.
Working with an old version of setuptools will bring issues in the future.

**Comment by bittner** [comment]
> But if the generation of MSI is disabled in recent versions of setuptools then I propose to drop the generation of MSI installers.

I tend to agree, but I don't think it's that critical of an issue. Setuptools is so widespread and rather old versions still work; I noticed this on some older projects of mine, especially when you build packages for older Python versions.

Personally, I would suggest to let this be the last shot of building EXE installers and MSI binaries and announce that EXE and MSI's may be discontinued in future. Currently, the build process for Windows runs both on AppVeyor and on GitHub Actions; you likely want to (consolidate or) remove this anyway, some day.

> Working with an old version of setuptools will bring issues in the future.

Note that the changes in this PR only ensure an older version for building the Windows EXE and MSI binaries. The artifacts that are uploaded to PyPI (and installed using pip) are not affected.

I'm not a fan of Mircosoft Windos, but let's keep it simple for their folks, as long as we can.

**Comment by LudovicRousseau** [comment]
Partly merged in 874603a9d6a5bb776a941700c2269be319809e6b

**Comment by bittner** [comment]
Good choice to remove building the EXE installer and the MSI! 👍  (I figured using them caused the dependency problems I originally came here for. 💡)

Thanks for merging!

**Pull request closed without merging**
